### PR TITLE
initialize folders for ag 2.0

### PR DESCRIPTION
**Pull request by dkirby-ms**

### CODE REVIEW

**Review by zaidmohd — APPROVED** [review]
LGTM

**Review by sebassem — CHANGES_REQUESTED** [review]
The folder structure PR is now merged, I think this PR needs to be adjusted to target the new structure

**Comment by fcabrera23** [comment]
@dkirby-ms  do we still need this one? Asking because we already merged https://github.com/Azure/arc_jumpstart_docs/pull/403

**Comment by dkirby-ms** [comment]
I've updated this to reflect the new folder structure.

This PR creates stubs for Agora 2.0 documentation

**Pull request closed without merging**
